// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQU4iP47yJV8x-9tn7dsdIJockCxTCxI',
    appId: '1:581582765163:web:a66f6b59290a0641ed052e',
    messagingSenderId: '581582765163',
    projectId: 'grabb-38bd6',
    authDomain: 'grabb-38bd6.firebaseapp.com',
    storageBucket: 'grabb-38bd6.firebasestorage.app',
    measurementId: 'G-W2JM2SXEFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTes8FQsBrlh2iRVBr0zDkm262vs_byCM',
    appId: '1:581582765163:android:6a11cad0c8cbe4c6ed052e',
    messagingSenderId: '581582765163',
    projectId: 'grabb-38bd6',
    storageBucket: 'grabb-38bd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTeZCcXi7Ts-nZina0nky8d8leohwAnw',
    appId: '1:581582765163:ios:1fe8f73ff01abf91ed052e',
    messagingSenderId: '581582765163',
    projectId: 'grabb-38bd6',
    storageBucket: 'grabb-38bd6.firebasestorage.app',
    iosBundleId: 'com.example.grabb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvQU4iP47yJV8x-9tn7dsdIJockCxTCxI',
    appId: '1:581582765163:web:c4ae190ccd543213ed052e',
    messagingSenderId: '581582765163',
    projectId: 'grabb-38bd6',
    authDomain: 'grabb-38bd6.firebaseapp.com',
    storageBucket: 'grabb-38bd6.firebasestorage.app',
    measurementId: 'G-BTX1P959DK',
  );
}
